#Make file for Homework 5

All: generator consumer dispatcher

generator: generator.cpp 
	g++ -Wall -g -o generator generator.cpp

consumer: consumer.cpp
	g++ -Wall -g -o consumer consumer.cpp

dispatcher: dispatcher.cpp
	g++ -Wall  -g -o dispatcher dispatcher.cpp
